server:
    port: 8080

spring:
    application:
        name: song a day
    datasource:
        url: jdbc:postgresql://localhost:5432/songaday
        username: <>
        password: <>
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    spotify:
                        client-id: <>
                        scope: user-read-email,user-read-private,user-read-currently-playing
                        authorization-grant-type: authorization_code
                        redirect-uri: http://127.0.0.1:8080/login/oauth2/code/spotify
                        client-authentication-method: none
                provider:
                    spotify:
                        authorization-uri: https://accounts.spotify.com/authorize
                        token-uri: https://accounts.spotify.com/api/token
                        user-info-uri: https://api.spotify.com/v1/me
                        user-name-attribute: id						
app:
    jwt:
        secret: <>
        expiration: <>
    frontend-url: <>

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.security.oauth2: TRACE
        org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE