server:
  port: 8080

spring:
  application:
    name: song a day
  datasource:
    url: <>
    username: <>
    password: <>
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: <>
            scope: user-read-email
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/spotify
            client-authentication-method: none
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
app:
  jwt:
    access-token-secret: <>
    refresh-token-secret: <>
    access-token-expiration-seconds: <>
    refresh-token-expiration-seconds: <>
  frontend-url: http://127.0.0.1:3000