server:
    port: 8080

spring:
    application:
        name: song a day
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    spotify:
                        client-id: <>
                        scope: user-read-email,user-read-private
                        authorization-grant-type: authorization_code
                        redirect-uri: <>
                        client-authentication-method: none
                provider:
                    spotify:
                        authorization-uri: https://accounts.spotify.com/authorize
                        token-uri: https://accounts.spotify.com/api/token
                        user-info-uri: https://api.spotify.com/v1/me
                        user-name-attribute: id						
app:
    jwt:
        secret: <>
        expiration: <>
    frontend-url: <>

logging:
    level:
        org.springframework.security: TRACE
        org.springframework.security.oauth2: TRACE
        org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE